// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: rpcpb/key.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KeyService_CertificateToNodeId_FullMethodName           = "/rpcpb.KeyService/CertificateToNodeId"
	KeyService_Secp256K1RecoverHashPublicKey_FullMethodName = "/rpcpb.KeyService/Secp256k1RecoverHashPublicKey"
	KeyService_Secp256K1Info_FullMethodName                 = "/rpcpb.KeyService/Secp256k1Info"
	KeyService_BlsSignature_FullMethodName                  = "/rpcpb.KeyService/BlsSignature"
)

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyServiceClient interface {
	CertificateToNodeId(ctx context.Context, in *CertificateToNodeIdRequest, opts ...grpc.CallOption) (*CertificateToNodeIdResponse, error)
	Secp256K1RecoverHashPublicKey(ctx context.Context, in *Secp256K1RecoverHashPublicKeyRequest, opts ...grpc.CallOption) (*Secp256K1RecoverHashPublicKeyResponse, error)
	Secp256K1Info(ctx context.Context, in *Secp256K1InfoRequest, opts ...grpc.CallOption) (*Secp256K1InfoResponse, error)
	BlsSignature(ctx context.Context, in *BlsSignatureRequest, opts ...grpc.CallOption) (*BlsSignatureResponse, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) CertificateToNodeId(ctx context.Context, in *CertificateToNodeIdRequest, opts ...grpc.CallOption) (*CertificateToNodeIdResponse, error) {
	out := new(CertificateToNodeIdResponse)
	err := c.cc.Invoke(ctx, KeyService_CertificateToNodeId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Secp256K1RecoverHashPublicKey(ctx context.Context, in *Secp256K1RecoverHashPublicKeyRequest, opts ...grpc.CallOption) (*Secp256K1RecoverHashPublicKeyResponse, error) {
	out := new(Secp256K1RecoverHashPublicKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_Secp256K1RecoverHashPublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Secp256K1Info(ctx context.Context, in *Secp256K1InfoRequest, opts ...grpc.CallOption) (*Secp256K1InfoResponse, error) {
	out := new(Secp256K1InfoResponse)
	err := c.cc.Invoke(ctx, KeyService_Secp256K1Info_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) BlsSignature(ctx context.Context, in *BlsSignatureRequest, opts ...grpc.CallOption) (*BlsSignatureResponse, error) {
	out := new(BlsSignatureResponse)
	err := c.cc.Invoke(ctx, KeyService_BlsSignature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility
type KeyServiceServer interface {
	CertificateToNodeId(context.Context, *CertificateToNodeIdRequest) (*CertificateToNodeIdResponse, error)
	Secp256K1RecoverHashPublicKey(context.Context, *Secp256K1RecoverHashPublicKeyRequest) (*Secp256K1RecoverHashPublicKeyResponse, error)
	Secp256K1Info(context.Context, *Secp256K1InfoRequest) (*Secp256K1InfoResponse, error)
	BlsSignature(context.Context, *BlsSignatureRequest) (*BlsSignatureResponse, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyServiceServer struct {
}

func (UnimplementedKeyServiceServer) CertificateToNodeId(context.Context, *CertificateToNodeIdRequest) (*CertificateToNodeIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CertificateToNodeId not implemented")
}
func (UnimplementedKeyServiceServer) Secp256K1RecoverHashPublicKey(context.Context, *Secp256K1RecoverHashPublicKeyRequest) (*Secp256K1RecoverHashPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Secp256K1RecoverHashPublicKey not implemented")
}
func (UnimplementedKeyServiceServer) Secp256K1Info(context.Context, *Secp256K1InfoRequest) (*Secp256K1InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Secp256K1Info not implemented")
}
func (UnimplementedKeyServiceServer) BlsSignature(context.Context, *BlsSignatureRequest) (*BlsSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlsSignature not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_CertificateToNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateToNodeIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CertificateToNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CertificateToNodeId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CertificateToNodeId(ctx, req.(*CertificateToNodeIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Secp256K1RecoverHashPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secp256K1RecoverHashPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Secp256K1RecoverHashPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Secp256K1RecoverHashPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Secp256K1RecoverHashPublicKey(ctx, req.(*Secp256K1RecoverHashPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Secp256K1Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secp256K1InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Secp256K1Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Secp256K1Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Secp256K1Info(ctx, req.(*Secp256K1InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_BlsSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlsSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).BlsSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_BlsSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).BlsSignature(ctx, req.(*BlsSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CertificateToNodeId",
			Handler:    _KeyService_CertificateToNodeId_Handler,
		},
		{
			MethodName: "Secp256k1RecoverHashPublicKey",
			Handler:    _KeyService_Secp256K1RecoverHashPublicKey_Handler,
		},
		{
			MethodName: "Secp256k1Info",
			Handler:    _KeyService_Secp256K1Info_Handler,
		},
		{
			MethodName: "BlsSignature",
			Handler:    _KeyService_BlsSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcpb/key.proto",
}
