// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: rpcpb/ping.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingServiceRequest) Reset() {
	*x = PingServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcpb_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServiceRequest) ProtoMessage() {}

func (x *PingServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServiceRequest.ProtoReflect.Descriptor instead.
func (*PingServiceRequest) Descriptor() ([]byte, []int) {
	return file_rpcpb_ping_proto_rawDescGZIP(), []int{0}
}

type PingServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *PingServiceResponse) Reset() {
	*x = PingServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcpb_ping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServiceResponse) ProtoMessage() {}

func (x *PingServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_ping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServiceResponse.ProtoReflect.Descriptor instead.
func (*PingServiceResponse) Descriptor() ([]byte, []int) {
	return file_rpcpb_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingServiceResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_rpcpb_ping_proto protoreflect.FileDescriptor

var file_rpcpb_ping_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x72, 0x70, 0x63, 0x70, 0x62, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x27, 0x0a, 0x13, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x32, 0x55, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x76,
	0x61, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61, 0x76, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x68, 0x65,
	0x2d, 0x72, 0x75, 0x73, 0x74, 0x2f, 0x61, 0x76, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x68, 0x65, 0x67,
	0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x3b, 0x72, 0x70,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcpb_ping_proto_rawDescOnce sync.Once
	file_rpcpb_ping_proto_rawDescData = file_rpcpb_ping_proto_rawDesc
)

func file_rpcpb_ping_proto_rawDescGZIP() []byte {
	file_rpcpb_ping_proto_rawDescOnce.Do(func() {
		file_rpcpb_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcpb_ping_proto_rawDescData)
	})
	return file_rpcpb_ping_proto_rawDescData
}

var file_rpcpb_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpcpb_ping_proto_goTypes = []interface{}{
	(*PingServiceRequest)(nil),  // 0: rpcpb.PingServiceRequest
	(*PingServiceResponse)(nil), // 1: rpcpb.PingServiceResponse
}
var file_rpcpb_ping_proto_depIdxs = []int32{
	0, // 0: rpcpb.PingService.PingService:input_type -> rpcpb.PingServiceRequest
	1, // 1: rpcpb.PingService.PingService:output_type -> rpcpb.PingServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_ping_proto_init() }
func file_rpcpb_ping_proto_init() {
	if File_rpcpb_ping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcpb_ping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcpb_ping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcpb_ping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_ping_proto_goTypes,
		DependencyIndexes: file_rpcpb_ping_proto_depIdxs,
		MessageInfos:      file_rpcpb_ping_proto_msgTypes,
	}.Build()
	File_rpcpb_ping_proto = out.File
	file_rpcpb_ping_proto_rawDesc = nil
	file_rpcpb_ping_proto_goTypes = nil
	file_rpcpb_ping_proto_depIdxs = nil
}
