name:  ci

# ref. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

permissions:
  contents: write

jobs:
  unit:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install linker
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check Rust version
        run: rustc --version
      # or use "abelfodil/protoc-action@v1"
      # ref. https://github.com/hyperium/tonic/issues/1047#issuecomment-1222508191
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run static analysis tests
        shell: bash
        run: scripts/tests.lint.sh
