name:  ci-clippy

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

permissions:
  contents: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install linker
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check Rust version
        run: rustc --version
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run static analysis tests
        shell: bash
        run: cargo fmt --all --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install linker
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check Rust version
        run: rustc --version
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run static analysis tests
        shell: bash
        run: cargo clippy --all --all-features --tests --benches --examples
