name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-avalanche-rs-crate:
    name: avalanche-rs-lib
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'v')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: publish avalanche-types crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-types
      - name: publish avalanche-consensus crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-consensus
