name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-avalanche-rs-crate:
    name: avalanche-rs-lib
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'v')"
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: publish avalanche-types crate
        continue-on-error: true
        shell: bash
        run: |
          ./scripts/check_crate_version.sh avalanche-types
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-types
      - name: publish avalanche-consensus crate
        continue-on-error: true
        shell: bash
        run: |
          ./scripts/check_crate_version.sh avalanche-consensus
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-consensus
