name: publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-avalanche-types-crate:
    name: publish-avalanche-types
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'avalanche-types-v')"
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: publish avalanche-types crate
        shell: bash
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-types
  publish-avalanche-consensus-crate:
    name: publish-avalanche-consensus
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'avalanche-consensus-v')"
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: publish avalanche-consensus crate
        shell: bash
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish -p avalanche-consensus

